# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='symptom',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
