# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180918_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sympton',
            new_name='Symptom',
        ),
    ]
